### PR TITLE
Syntax highlighter

### PR DESCRIPTION
**Pull request by gruelingpine185**
I thought it would be nice (and more scalable) to have JavaScript handle the highlighting and conversion to HTML through the DOM rather than manually.

# TODO
- [x] Read/create tokens from string
  - [x] Handle separators, operators, other tokens 
  - [x] Create lines
  - [x] Fill lines with tokens
  - [x] Create and fill code blocks
  - [x] Generate comment tokens
  - [x] Make a more manageable way to run `createCodeBlock()`

### CODE REVIEW

**Comment by gruelingpine185** [comment]
Hey Rei, I've done quite a bit so far building the syntax highlighter which is thankfully coming together. After over 5hrs of trying to figure out why I couldn't get the lexer to properly collect and build a C-style comment, I did it! However, to speed things up a bit, would you mind helping to capture and create tokens for the remaining characters? There should be operators, separators (like `{}`, `()`), and terminators (like `;`) left, but probably more. Oh and escape characters (if you want those highlighted also). It would be appreciated.

**Comment by gruelingpine185** [comment]
I'll continue doing what I can in the mean time, refactoring, removing reoccurring code, etc. All the excerpts can be found under `noch/script.js`, which also contains the code for running the highlighter. The brains of the operation is, of course, in `noch/syntax-highlighter.js`. I didn't bother creating the macros with JS because they are (and should ideally be) small enough to build by hand. At the time of writing this, commit `a1ee501` ([what I have so far](https://github.com/LordOfTrident/LordOfTrident.github.io/pull/3/commits/a1ee501598cc68c851ef62d16b4b0f9c24fd0599)) is the latest

**Comment by LordOfTrident** [comment]
Thank you for the help, but sorry im not home currently, so i cant work on projects.

**Comment by gruelingpine185** [comment]
It's ok. Umm, I was thinking what if you make all you documentation within the code? That way people in IDEs or environments where they have the ability to hover over certain items will provide documentation. I can see this being really helpful where internet connection isn't guaranteed. If we were to to that, we now have to figure out how to keep the inline docs in sync with the docs on the website. Now, this may be unnecessary for a project of its current scale, but what if we make use of Github's API so we can feed source code to the highlighter through the API, which in turn creates the documentation for the website? I've never used the API before, but It would make for a good learning opportunity.

**Comment by gruelingpine185** [comment]
I haven't tested for edge cases yet, but the main functionality is present. LMK what u think about the idea in the previous comment when u get a chance

**Comment by LordOfTrident** [comment]
I think without an internet connection youre screwed anyways :D jokes aside, sure i can write the documentation in the headers with comments. I know nothing about the github API, but something to keep it in sync would be handy, since theres quite a few libraries that i plan on making for this project. Im gonna work on a JSON parser library next.

**Comment by LordOfTrident** [comment]
Btw do you have a discord or something? talking over pull requests is kinda slow

**Comment by gruelingpine185** [comment]
I do. It's was originally `gruelingpine185#9735` (or something like that), but now its just `gruelingpine185`.

**Pull request merged**
